= Fazit und Ausblick

Im Rahmen dieser Arbeit wurde eine modulare Plattform für den Einsatz eines Quadrocopters in der akademischen Lehre konzipiert, realisiert und experimentell evaluiert. Den Ausgangspunkt bildeten die Entwicklung der Avionik sowie der Aufbau einer Softwarearchitektur, die eine flexible Implementierung und Evaluierung unterschiedlicher Regelungsverfahren ermöglicht. Die entwickelte Onboard-Software erlaubt es, in Simulink generierten Code für die Regelungsalgorithmen direkt zu integrieren und in Echtzeit auf dem Quadrocopter auszuführen. Als Gegenstück fungiert eine Bodenstationssoftware, die neben der Flugdatenerfassung und -visualisierung auch die Parametrierung der Regler sowie die Durchführung koordinierter Flugtests unterstützt.

Ein zentraler Bestandteil der Arbeit war die Modellbildung des Quadrocopters, bei der ein physikalisch motiviertes, nichtlineares Zustandsraummodell hergeleitet wurde. Durch eine Kombination aus klassischer Identifikation auf Testständen und datengetriebener Optimierung im geschlossenen Regelkreis konnte das Modell präzise parametriert und der Sim-to-Real-Gap signifikant reduziert werden. Das resultierende linearisierte Modell bildete die Grundlage für den Entwurf modellbasierter Regler.

Im direkten Vergleich wurden ein LQR mit integraler Ausgangsrückführung sowie klassische PID-Regler für die Lage- und Positionsregelung implementiert. Während der PID-Regler durch seine einfache Struktur überzeugt, bietet der LQR Vorteile hinsichtlich einer systematischen Auslegung und einer optimalen Regelgüte. Beide Algorithmen erlaubten die Stabilisierung des Systems und die Verfolgung der vorgegebenen Referenztrajektorien. Die Plattform konnte somit erfolgreich unter Beweis stellen, dass sie eine praxisnahe Gegenüberstellung verschiedener Regelungsansätze erlaubt.

Trotz der erzielten Ergebnisse bestehen weiterhin Möglichkeiten zur Verbesserung und Erweiterung des Systems. So könnte die Modellgenauigkeit durch die Berücksichtigung zusätzlicher Effekte wie aerodynamischer Kopplungen oder der Dynamik des Antriebssystem weiter erhöht werden. Auf Basis des bereits vorliegenden parametrisierten, linearen Zustandsraummodells wäre die Implementierung komplexerer Verfahren, wie der modellprädiktiven Regelung (MPC) oder adaptiver Regler, ein konsequenter nächster Schritt, der eine Leistungssteigerung bewirken und fortgeschrittene Lehrinhalte abdecken könnte.

Ein wesentlicher Fokus zukünftiger Arbeiten sollte auf der Optimierung des Messsystems liegen. Die Entwicklung eines eigenen Fusionsalgorithmus für Gyroskop- und Beschleunigungsdaten würde es erlauben, die systeminterne Begrenzung des Digital Motion Processors von 200 Hz zu umgehen und höhere Abtastraten zu erzielen. Hierbei könnte das entwickelte Systemmodell (z. B. im Rahmen eines Kalman-Filters) integriert werden, um die Zustandsschätzung zu verbessern. Zur Kompensation des langfristigen Drifts der Gierrate ist zudem die Integration eines Magnetometers zur Bestimmung der absoluten Ausrichtung sinnvoll.

Zusammenfassend stellt die entwickelte Plattform eine solide Grundlage für die Lehre der Regelungstechnik dar. Sie verbindet theoretische Konzepte mit praktischer Umsetzung und ermöglicht es, komplexe Zusammenhänge anschaulich zu vermitteln. Gleichzeitig bietet sie ausreichend Flexibilität, um zukünftige Entwicklungen und Forschungsideen zu integrieren, und schafft damit eine nachhaltige Basis für den weiteren Einsatz in Lehre und Forschung.
